name: Daily UV → Excel → Upload Automation

permissions:
  contents: write  # allows saving log and xlsx files

on:
  schedule:
    - cron: "0 6 * * *"  # daily 6:00 UTC
  workflow_dispatch:

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Run main script
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: python main.py

      - name: Commit results (logs + xlsx)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add logs/ xlsx_files/
          git commit -m "daily: add logs and reports for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
